
# bogster, dark_plus, everforest_dark, fleet_dark, github_dark_high_contrast, gruvbox_dark_hard, merionette, pop-dark, snazzy
theme = "mytheme"

[editor]
# Highlight all lines with cursors
cursorline = true
true-color = true

[editor.file-picker]
hidden = false

[editor.indent-guides]
# render=true

[editor.lsp]
display-messages = true

[editor.statusline]
left = [
  "mode",
  "spinner",
  "version-control",
  "file-name",
  "file-modification-indicator"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]

[editor.soft-wrap]
enable = true

[editor.whitespace.render]
# space = "all"
tab = "all"

[keys.normal]
C-j = "save_selection"
