
theme = "mytheme"

[editor]
# Highlight all lines with cursors
cursorline = true
true-color = true

[editor.file-picker]
hidden = false

[editor.indent-guides]
# render=true

[editor.lsp]
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[editor.soft-wrap]
enable = true

[editor.whitespace.render]
# space = "all"
tab = "all"
