
# ltex language server also works with markdown and includes spell checking
[language-server.ltex-ls]
command = "ltex-ls"

# AI coding assistant
[language-server.tabby]
command = "npx"
args = ["tabby-agent", "--lsp", "--stdio"]

# Adding typos-lsp language server for spell checking
[language-server.typos-lsp]
command = "typos-lsp"

[[language]]
name = "bash"
language-servers = [ "bash-language-server", "typos-lsp" ]

[[language]]
name = "c"
language-servers = [ "clangd", "typos-lsp", "tabby" ]

[[language]]
name = "cpp"
language-servers = [ "clangd", "typos-lsp", "tabby" ]

[[language]]
name = "jinja"
language-servers = [ "typos-lsp" ]

[[language]]
name = "markdown"
language-servers = [ "marksman", "ltex-ls" ]

[[language]]
name = "python"
language-servers = [ "ruff", "jedi-language-server", "pylsp", "typos-lsp", "tabby" ]

[[language]]
name = "toml"
language-servers = [ "taplo", "typos-lsp" ]

[[language]]
name = "xml"
language-servers = [ "typos-lsp" ]

#================ Experimental =============#

[language-server.erg-lsp]
command = "erg"
args = ["server"]

[[language]]
name = "erg"
scope = "source.erg"
file-types = ["er"]
shebangs = ["erg"]
comment-tokens = "#"
block-comment-tokens = { start = "'''", end = "'''" }
indent = { tab-width = 4, unit = "    " }
language-servers = [ "erg-lsp" ]

[language-server.roc-ls]
command = "roc_language_server"

[[language]]
name = "roc"
scope = "source.roc"
injection-regex = "roc"
file-types = ["roc"]
shebangs = ["roc"]
roots = []
comment-token = "#"
language-servers = ["roc-ls"]
indent = { tab-width = 2, unit = "  " }
auto-format = true
formatter = { command = "roc", args =[ "format", "--stdin", "--stdout"]}


[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
[[grammar]]

name = "roc"
source = { git = "https://github.com/faldor20/tree-sitter-roc.git", rev = "0b1afe88161cbd81f5ddea1bb4fa786314ed49a7" }

