inherits = "base16_transparent"

"ui.popup" = { bg = "background2" }

"ui.selection" = { bg = "background3" }
"ui.selection.primary" = { bg = "background4" }
"ui.statusline" = { bg = "background3" }

[palette]

background2 = "#440044"
background3 = "#440044"
background4 = "#880088"
